### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by satshabad-cr** [cjoudrey/graphql-schema-linter#170]
It looks like you may have hit a bug in graphql-schema-linter.

It would be super helpful if you could report this here: https://github.com/cjoudrey/graphql-schema-linter/issues/new

TypeError: Cannot read property '0' of undefined
    at /usr/local/lib/node_modules/graphql-schema-linter/lib/runner.js:76:70
    at Array.reduce (<anonymous>)
    at groupErrorsBySchemaFilePath (/usr/local/lib/node_modules/graphql-schema-linter/lib/runner.js:75:17)
    at run (/usr/local/lib/node_modules/graphql-schema-linter/lib/runner.js:67:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/graphql-schema-linter/lib/cli.js:15:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by cjoudrey** [comment]
Hey @satshabad-cr! Sorry you ran into this issue. Could you possible provide the schema you used and the options you used to run the linter? This would be super helpful to reproduce the bug.

**Comment by satshabad-cr** [comment]
Unfortunately I can't reproduce the schema I was testing it on :/, not sure what I had to make it produce this error

**Comment by cjoudrey** [comment]
No worries. I will close the issue for now. Please re-open it if you run into the issue again and can reproduce it. 😄
