### ISSUE TITLE
Linter not working after updating to 1.0.0

### ISSUE THREAD

**Issue by lillem4n** [cjoudrey/graphql-schema-linter#252]
I get the following error in my console:

```
It looks like you may have hit a bug in graphql-schema-linter.

It would be super helpful if you could report this here: https://github.com/cjoudrey/graphql-schema-linter/issues/new

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at ignoreListErrorFilter (/home/lilleman/.../node_modules/graphql-schema-linter/lib/validator.js:143:39)
    at validateSchemaDefinition (/home/lilleman/.../node_modules/graphql-schema-linter/lib/validator.js:72:68)
    at run (/home/lilleman/.../node_modules/graphql-schema-linter/lib/runner.js:68:58)
```

**Comment by lillem4n** [comment]
Duplicate of https://github.com/cjoudrey/graphql-schema-linter/issues/250
