### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by sbienkow-ninja** [cjoudrey/graphql-schema-linter#308]
After installing following packages:
```sh
$ npm install -g graphql-schema-linter@3.0.0 graphql@16.3.0
```

And running the `graphql-schema-linter`:
```sh
$ graphql-schema-linter **/*.graphql
It looks like you may have hit a bug in graphql-schema-linter.

It would be super helpful if you could report this here: https://github.com/cjoudrey/graphql-schema-linter/issues/new

TypeError: Cannot read property '0' of undefined
    at /opt/hostedtoolcache/node/14.19.1/x64/lib/node_modules/graphql-schema-linter/lib/validator.js:79:23
    at Array.sort (<anonymous>)
    at sortErrors (/opt/hostedtoolcache/node/14.19.1/x64/lib/node_modules/graphql-schema-linter/lib/validator.js:78:17)
    at validateSchemaDefinition (/opt/hostedtoolcache/node/14.19.1/x64/lib/node_modules/graphql-schema-linter/lib/validator.js:71:24)
    at run (/opt/hostedtoolcache/node/14.19.1/x64/lib/node_modules/graphql-schema-linter/lib/runner.js:68:58)
Error: Process completed with exit code 3.
```

I hate to post such empty issue, but no clue what more information I could include (apart from the `.graphql` files which I can't make public).

**Comment by modosc** [comment]
we hit it too. i added some debugging in `lib/validator.js`:
```
function sortErrors(errors) {
  console.log({ errors: errors.filter(e => !e.locations) })
  return errors.sort((a, b) => {
    return a.locations[0].line - b.locations[0].line;
  });
}
```
and (ironically) this seems to be one error that's exploding for me:
```
  errors: [
    GraphQLError: Too many validation errors, error limit reached. Validation aborted.
        at ValidationContext._onError (/Users/jonathan.schatz/git/data-spec/node_modules/graphql/validation/validate.js:73:11)
        at ValidationContext.reportError (/Users/jonathan.schatz/git/data-spec/node_modules/graphql/validation/ValidationContext.js:36:10)
        at Object.FieldDefinition (/Users/jonathan.schatz/git/data-spec/node_modules/graphql-schema-linter/lib/rules/fields_have_descriptions.js:23:15)
        at Object.enter (/Users/jonathan.schatz/git/data-spec/node_modules/graphql/language/visitor.js:301:32)
        at Object.enter (/Users/jonathan.schatz/git/data-spec/node_modules/graphql/utilities/TypeInfo.js:391:27)
        at visit (/Users/jonathan.schatz/git/data-spec/node_modules/graphql/language/visitor.js:197:21)
        at validate (/Users/jonathan.schatz/git/data-spec/node_modules/graphql/validation/validate.js:91:24)
        at validateSchemaDefinition (/Users/jonathan.schatz/git/data-spec/node_modules/graphql-schema-linter/lib/validator.js:70:43)
        at run (/Users/jonathan.schatz/git/data-spec/node_modules/graphql-schema-linter/lib/runner.js:68:58) {
      path: undefined,
      locations: undefined,
      extensions: [Object: null prototype] {}
    }
  ]
```

**Comment by cjoudrey** [comment]
Ah, darn. 😢 It would definitely be easier to debug this with a schema.

It could be worth double checking if this happens with `graphql@15.8.0`.

Even better, if you can make it crash with a shareable subset of your schema that would make fixing this easier.

Is there anything about your schema that might be out of the ordinary? I ask because I've got a series of small fake schemas that work fine.

**Comment by cjoudrey** [comment]
Thanks for the debugging! 🙂

I suspect that might be the issue, but the linter should gracefully handle this. Crashing is not a great user experience.

Comment descriptions have been deprecated for some time now. As per GraphQL 16.x, I believe comment descriptions were officially removed and replaced with [string literal descriptions](https://spec.graphql.org/draft/#sec-Descriptions). I'll need to confirm this is the issue once I am in front of my computer.

Hope that helps for now.

**Comment by modosc** [comment]
i also checked and even with all `#` comments removed we still get the error. 

i wonder if just fixing `sortErrors` to handle `path: undefined` would help?

**Comment by cjoudrey** [comment]
This issue should be addressed by: https://github.com/cjoudrey/graphql-schema-linter/pull/309.

I'll make a release shortly.
