### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'inherits')

### ISSUE THREAD

**Issue by FerasAlazzeh** [cjoudrey/graphql-schema-linter#316]
It looks like you may have hit a bug in graphql-schema-linter.

It would be super helpful if you could report this here: https:/github.com/cjoudrey/graphql-schema-linter/issues/new

TypeError: Cannot read properties of undefined (reading 'inherits')
    at /node_modules/graphql-lint-rules/rules/index-34b81f35.js:2568:8
    at createCommonjsModule (/mnt/node_modules/graphql-lint-rules/rules/index-34b81f35.js:582:9)
    at Object.<anonymous> (/node_modules/graphql-lint-rules/rules/index-34b81f35.js:2556:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/node_modules/graphql-lint-rules/rules/compositeFieldsAreNullable.js:14:13)
Expecting value: line 1 column 1 (char 0)

**Comment by Patr56** [comment]
its look like fix in [v3.0.1](https://github.com/cjoudrey/graphql-schema-linter/releases/tag/v3.0.1)

**Comment by steverice** [comment]
@FerasAlazzeh I believe this is an issue with the `graphql-lint-rules` package, not `graphql-schema-linter` itself: https://github.com/pinterest/graphql-lint-rules/pull/35

**Comment by cjoudrey** [comment]
Thanks for the reply @steverice. I'm going to close the issue as I believe you are correct.

The backtrace seems to suggest the same thing as well.

```
at /node_modules/graphql-lint-rules/rules/index-34b81f35.js:2568:8
```

Feel free to re-open if I'm mistaken.
