### ISSUE TITLE
TypeError: typeInfo.enter is not a function

### ISSUE THREAD

**Issue by glensc** [cjoudrey/graphql-schema-linter#332]
```
➜ yarn graphql-schema-linter --comment-descriptions
yarn run v1.22.19
$ ./node_modules/.bin/graphql-schema-linter --comment-descriptions
It looks like you may have hit a bug in graphql-schema-linter.

It would be super helpful if you could report this here: https://github.com/cjoudrey/graphql-schema-linter/issues/new

TypeError: typeInfo.enter is not a function
    at Object.enter (./node_modules/graphql/language/visitor.js:369:16)
    at visit (./node_modules/graphql/language/visitor.js:242:26)
    at validate (./node_modules/graphql/validation/validate.js:73:24)
    at validateSchemaDefinition (./node_modules/graphql-schema-linter/lib/validator.js:76:43)
    at run (./node_modules/graphql-schema-linter/lib/runner.js:68:58)
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
➜ cat .graphql-schema-linterrc
{
  "rules": [
    "defined-types-are-used",
    "deprecations-have-a-reason",
    "enum-values-have-descriptions",
    "fields-have-descriptions",
    "input-object-values-have-descriptions",
    "types-are-capitalized",
    "types-have-descriptions"
  ],
  "schemaPaths": [
    "schemas/*.graphql"
  ]
}
```

```
✖ cat schemas/query.graphql
type IpLookup {
  country: String!
  ip: String!
}

type Query {
  lookup(
    ip: String!
  ): IpLookup
}
```

I was updating my dependency:

```diff
-    "graphql-schema-linter": "^0.5.0",
+    "graphql-schema-linter": "^3.0.1",
```

**Comment by schneider10** [comment]
Is this package no longer maintained?
