### ISSUE TITLE
Support for imports

### ISSUE THREAD

**Issue by patrick91** [cjoudrey/graphql-schema-linter#80]
Hi, I've tried running graphql-schema-linter on multiple files with the latest version of [graphql](https://github.com/graphql/graphql-js) but the linting breaks with this error:

```
It looks like you may have hit a bug in graphql-schema-linter.

It would be super helpful if you could report this here: https://github.com/cjoudrey/graphql-schema-linter/issues/new

Error: Query root type must be provided.
    at assertValidSchema (/Users/patrick/Documents/Github/graphql-mock/node_modules/graphql/type/validate.js:78:11)
    at validate (/Users/patrick/Documents/Github/graphql-mock/node_modules/graphql/validation/validate.js:61:35)
    at validateSchemaDefinition (/Users/patrick/Documents/Github/graphql-mock/node_modules/graphql-schema-linter/lib/validator.js:30:41)
    at run (/Users/patrick/Documents/Github/graphql-mock/node_modules/graphql-schema-linter/lib/runner.js:64:56)
    at Object.<anonymous> (/Users/patrick/Documents/Github/graphql-mock/node_modules/graphql-schema-linter/lib/cli.js:15:32)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

Which seems to be caused by this: https://github.com/graphql/graphql-js/pull/1124

My workaround was to merge all the files with AWK and lint the merged schema,
`awk 'FNR==1{print ""}1' ../api/**/*.graphql | graphql-schema-linter .graphql -s`

I'm not sure what the best solution to fix this will be, I know there is no official syntax for imports, but there are two "proposal":

- https://github.com/graphcool/graphql-import
- https://github.com/apollographql/graphql-tag/blob/master/loader.js#L9-L40

I think add some kind of imports support would be great, the only issue is that we still have the error from above, since now the GraphQL library needs a root type. Another solution would be do merge (like I did with the awk) all the files and run the validation on it. Then we need to a mapping between the merged file and the original ones, but shouldn't be difficult :)

What do you think? I might have some time to help this or the next week

**Comment by patrick91** [comment]
I just found out that this is already working, if you pass a glob the library will concatenate all the files :)

https://github.com/cjoudrey/graphql-schema-linter/blob/55bdcd4ce28c634372110a2d53d1393c61303ab8/src/configuration.js#L33-L62

**Comment by chapati23** [comment]
@patrick91 how exactly did you get it working?

i'm trying `graphql-schema-linter src/**/*.graphql` and always get:

`Error: Type "Query" was defined more than once.`

However, adding `extend`s to all my modularly defined `Query`s then breaks `graphql-import`.

Seems there's no way to make both tools happy at the moment :-/
